name: GoldmanCentral
version: ${version}
main: lee.code.central.Central
api-version: 1.19
author: Lee
folia-supported: true
commands:
  gamemode:
    description: Change your gamemode.
    permission: central.command.gamemode
    aliases: [gm]
    usage: "/gamemode &f<gamemode>"
  fly:
    description: Toggles your ability to fly.
    permission: central.command.fly
    usage: "/fly"
  weather:
    description: Changes the weather in the world you're in.
    permission: central.command.weather
    usage: "/weather &f<clear/thunder/rain>"
  smite:
    description: Summon lightning on a player or location.
    permission: central.command.smite
    usage: "/smite &f<player>"
  enchant:
    description: Enchant the item you're holding.
    permission: central.command.enchant
    usage: "/enchant &f<enchantment> <level>"