name: GoldmanCentral
version: ${version}
main: lee.code.central.Central
api-version: 1.19
author: Lee
folia-supported: true
depend: [GoldmanEconomy]
commands:
  gamemode:
    description: Change your gamemode.
    permission: central.command.gamemode
    aliases: [gm]
    usage: "/gamemode &f<gamemode>"
  fly:
    description: Toggles your ability to fly.
    permission: central.command.fly
    usage: "/fly"
  flyspeed:
    description: Adjust your fly speed.
    permission: central.command.flyspeed
    usage: "/flyspeed &f<speed>"
  weather:
    description: Changes the weather in the world you're in.
    permission: central.command.weather
    usage: "/weather &f<clear/thunder/rain>"
  smite:
    description: Summon lightning on a player or location.
    permission: central.command.smite
    usage: "/smite &f<player>"
  enchant:
    description: Enchant the item you're holding.
    permission: central.command.enchant
    usage: "/enchant &f<enchantment> <level>"
  give:
    description: Give a target user a item.
    permission: central.command.give
    usage: "/give &f<player> <material> <amount>"
  spawner:
    description: Give a target user a spawner.
    permission: central.command.spawner
    usage: "/spawner &f<player> <entity> <amount>"
  head:
    description: Create a player head with any username.
    permission: central.command.head
    usage: "/head &f<player>"
  glow:
    description: Toggle your glow.
    permission: central.command.glow
    usage: "/glow"
  heal:
    description: Heal yourself or a online player.
    permission: central.command.heal
    usage: "/heal &f<player>"
  seen:
    description: Last time a target player joined the server.
    permission: central.command.seen
    usage: "/seen &f<player>"
  colors:
    description: A list of color codes that can be used.
    permission: central.command.colors
    usage: "/colors"
  balance:
    description: Check your balance or a target player's balance.
    permission: central.command.balance
    aliases: [bal]
    usage: "/balance &f<player>"
  money:
    description: Alter a players balance.
    permission: central.command.money
    aliases: [eco]
    usage: "/money &f<player> <set/add/remove> <amount>"
  worth:
    description: Check the worth of the item you're holding.
    permission: central.command.worth
    usage: "/worth"
  sell:
    description: Sell the item you're holding to the server.
    permission: central.command.sell
    usage: "/sell"
  pay:
    description: Pay another player from your balance.
    permission: central.command.pay
    usage: "/pay &f<player> <amount>"
  feed:
    description: Feed yourself or another player.
    permission: central.command.feed
    usage: "/feed &f<player>"
  spawn:
    description: Teleport to the server spawn.
    permission: central.command.spawn
    usage: "/spawn"
  setspawn:
    description: Set the server spawn.
    permission: central.command.setspawn
    usage: "/setspawn"
  clear:
    description: Clear your inventory.
    permission: central.command.clear
    usage: "/clear"